git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editPreset: "nvim"

keybinding:
  # universal:
  # exit: '<esc>'
  # return: 'q'

  commits:
    moveDownCommit: "<c-n>" # move commit down one
    moveUpCommit: "<c-p>" # move commit up one

confirmOnQuit: false
quitOnTopLevelReturn: false
