git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: true

os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} {{filename}}"

keybinding:
  # universal:
  # exit: '<esc>'
  # return: 'q'

  commits:
    moveDownCommit: "<c-n>" # move commit down one
    moveUpCommit: "<c-p>" # move commit up one

confirmOnQuit: false
quitOnTopLevelReturn: false
