# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    extraModulePackages = [ ];
    kernelModules = [ "kvm-amd" ];
    initrd = {
      availableKernelModules =
        [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ "amdgpu" ];
    };
  };

  hardware.keyboard.zsa.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9f6320b0-d42c-4e33-9ac5-0e5a48e7ef10";
    fsType = "btrfs";
    options = [ "compress=zstd" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2e507670-4760-484c-8932-fb205929fb37";
    fsType = "btrfs";
    options = [ "compress=zstd" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1890-3639";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/53e11865-70bc-4368-88d0-25d52b6add29"; }];

  services = {
    xserver = {
      videoDrivers = [ "amdgpu" ];
    };
  };

  networking = {
    hostName = "mzhukov-laptop"; # Define your hostname.
  };
}
