abbr --add make "dmake"
abbr --add mtkcom "pico -b 57600"
abbr --add rlxcom "pico -b 38400"
abbr --add rlx9607com "pico -b 115200"

abbr --add rt "redminer timer"
abbr --add rts "redminer timer status"
abbr --add rtst "rts date today"
abbr --add rtsa "rts active"
abbr --add rtn "redminer timer new"
abbr --add rtc "redminer timer commit"
abbr --add rte "redminer timer batch 0"
abbr --add rf "redminer fetch"
abbr --add rgc "redminer gc"
abbr --add q "quilt"
abbr --add vrg "rg --no-heading --column"
abbr --add xclipa "xclip -sel clip"
