[battery]
format = "[$symbol $percentage]($style) "

[cmake]
disabled = true

[directory]
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"

[git_status]
ahead = "↑${count}"
behind = "↓${count}"
deleted = "✘${count}"
diverged = "↑${ahead_count}↓${behind_count}"
modified = "✚${count}"
renamed = "»${count}"
staged = "●${count}"
stashed = "⚑${count}"
untracked = "…${count}"

[lua]
disabled = true

[memory_usage]
disabled = false
threshold = 75

[status]
disabled = false
